const EN_COPY = {
  'page.title': 'MissionBraid · Agent Runtime Workbench',
  'nav.skipToMission': 'Skip to Mission details',
  'brand.eyebrow': 'Mission runtime workbench',
  'brand.subtitle': 'A Mission belongs to the Mission—not to one CLI.',
  'brand.continuity': 'MISSION CONTINUITY',
  'language.ariaLabel': 'Language',
  'connection.connecting': 'Connecting to the local control plane',
  'connection.connected': 'Local control plane connected',
  'connection.disconnected': 'Local control plane disconnected',
  'runtime.eyebrow': 'Runtime inventory',
  'runtime.heading': 'Local runtimes',
  'runtime.refresh': 'Refresh inventory',
  'runtime.loading': 'Detecting Codex, Qoder, and other local Harnesses…',
  'runtime.empty': 'No Runtime found. Install and sign in to Codex or Qoder, then refresh.',
  'runtime.nameFallback': 'Runtime',
  'runtime.versionFallback': 'version —',
  'runtime.stateFallback': 'Status unknown',
  'runtime.status.ready-supported': 'Ready · can run Missions',
  'runtime.status.installed-unavailable': 'Installed · currently unavailable',
  'runtime.status.installed-unsupported': 'Detected · not connected to Missions yet',
  'runtime.status.needs-bootstrap': 'Harness detected · startup command required',
  'runtime.status.missing': 'Not found on this machine',
  'runtime.capabilitiesHeading': 'Adapter capability boundary',
  'runtime.capability.observe': 'Observe',
  'runtime.capability.interrupt': 'Interrupt',
  'runtime.capability.steer': 'Steer',
  'runtime.capability.gate': 'Pre-tool gate',
  'runtime.capability.resume': 'Resume',
  'runtime.capability.fork': 'Native fork',
  'runtime.capability.restore': 'Workspace restore',
  'runtime.capability.effectControl': 'Effect control',
  'runtime.capability.status.supported': 'Supported',
  'runtime.capability.status.unsupported': 'Unsupported',
  'runtime.capability.status.unknown': 'Unknown',
  'runtime.capability.control.native': 'Native',
  'runtime.capability.control.controller': 'Controller',
  'runtime.capability.control.cooperative': 'Cooperative',
  'runtime.capability.control.observe-only': 'Observe only',
  'runtime.capability.control.none': 'No control',
  'runtime.capability.control.unknown': 'Control unknown',
  'mission.indexEyebrow': 'Mission index',
  'mission.indexHeading': 'Missions',
  'mission.refreshAria': 'Refresh Mission list',
  'mission.loading': 'Loading Missions…',
  'mission.empty': 'No Missions yet. Complete the form to start the first task across Runtimes.',
  'mission.untitled': 'Untitled Mission',
  'mission.noSelectionEyebrow': 'No Mission selected',
  'mission.noSelectionTitle': 'Move one task across multiple Runtimes',
  'mission.noSelectionBody':
    'Select an existing Mission on the left or create one on the right. Attempts, Capsules, Effects, and Receipts appear here in their real order.',
  'mission.detailLoading': 'Loading Mission details…',
  'mission.detailInvalid': 'The Mission detail format is not recognized.',
  'mission.objectiveMissing': 'This Mission has no objective summary to display.',
  'mission.authoritativeEyebrow': 'Authoritative Mission',
  'mission.start': 'Start execution',
  'mission.continue': 'Continue Mission',
  'mission.reverify': 'Verify again',
  'mission.lastRunFailed': 'The last run did not finish: {error}',
  'mission.lastRunErrorFallback': 'No error summary was returned',
  'mission.controllerInterrupted':
    'The Workbench stopped before the Mission finished. Continue from the last persisted event.',
  'mission.commandQueued':
    'The command is durably queued and will start when the local coordinator claims it.',
  'mission.status.pending': 'Pending',
  'mission.status.queued': 'Queued',
  'mission.status.running': 'Running',
  'mission.status.waiting': 'Waiting to continue',
  'mission.status.verifying': 'Verifying',
  'mission.status.succeeded': 'Verified',
  'mission.status.failed': 'Not verified',
  'mission.status.cancelled': 'Cancelled',
  'mission.status.interrupted': 'Interrupted · can continue',
  'mission.status.unknown': 'Unknown',
  'composer.eyebrow': 'Compose',
  'composer.heading': 'Braid a new Mission',
  'composer.submitOnce': 'One submission',
  'form.titleLabel': 'Title',
  'form.titlePlaceholder': 'Fix browser task persistence',
  'form.objectiveLabel': 'What outcome do you want?',
  'form.objectivePlaceholder':
    'Describe the final verifiable code outcome. You do not need to break the work into Runtime steps.',
  'form.workspaceLabel': 'Absolute path to the Git workspace',
  'form.workspacePlaceholder': '/Users/me/project-worktree',
  'form.verifierHeading': 'Completion criteria',
  'form.verifierHint': 'The control plane runs the program directly, without a Shell.',
  'form.executableLabel': 'Executable',
  'form.argumentsLabel': 'Arguments · one per line',
  'form.routeLegend': 'Runtime route',
  'form.singleAttempt': 'Single Attempt',
  'form.plannedHandoff': 'Planned Capsule handoff',
  'form.threeRuntimeHandoff': 'Three-stage Capsule handoff',
  'form.profileSummary': 'Runtime Profile',
  'form.profileHint':
    'A Harness is only the runner; the model, reasoning effort, and permissions define the effective execution environment.',
  'form.modelLabel': 'Model',
  'form.reasoningLabel': 'Reasoning',
  'form.createAndRun': 'Create and run Mission',
  'form.creating': 'Creating the Mission and binding its original completion criteria…',
  'form.created': 'Mission created and running. Progress appears in the center timeline.',
  'form.createFailed': 'The Mission was not created. Check the inputs and try again.',
  'validation.titleRequired': 'Title is required.',
  'validation.objectiveRequired': 'Objective is required.',
  'validation.workspaceRequired': 'Workspace path is required.',
  'validation.workspaceAbsolute': 'Workspace path must be absolute.',
  'validation.workspaceDirectory': 'Workspace path must point to a directory.',
  'validation.workspaceGitRoot': 'Workspace path must be the root of a Git worktree.',
  'validation.verifierRequired': 'Verifier executable is required.',
  'validation.verifierDirect': 'Run the verifier directly instead of through a Shell.',
  'validation.codexModelRequired': 'Codex model is required.',
  'validation.codexReasoningRequired': 'Codex reasoning is required.',
  'validation.qoderModelRequired': 'Qoder model is required.',
  'validation.qoderReasoningRequired': 'Qoder reasoning is required.',
  'validation.claudeModelRequired': 'Claude Code model is required.',
  'validation.claudeReasoningRequired': 'Claude Code reasoning is required.',
  'route.modelUnset': 'model not set',
  'route.reasoningUnset': 'reasoning not set',
  'timeline.eyebrow': 'Evidence timeline',
  'timeline.heading': 'Attempt · Capsule · Effect · Receipt',
  'timeline.oneEvent': '1 EVENT',
  'timeline.manyEvents': '{count} EVENTS',
  'timeline.pending': 'The Mission exists. Real events will appear here after execution starts.',
  'timeline.empty': 'The current API response has no timeline to display.',
  'timeline.recordFallback': 'Execution record',
  'timeline.viewKernelRecord': 'View Kernel record',
  'timeline.unserializable': 'The record could not be serialized',
  'timeline.description.attemptStarted': '{harness} started the current stage.',
  'timeline.description.attemptFinished': 'This Attempt left a traceable result.',
  'timeline.description.profileSelected': '{harness} is using the {model} Profile.',
  'timeline.description.checkpointCreated':
    'Workspace state was frozen so the next Runtime can continue from this verifiable boundary.',
  'timeline.description.handoffPrepared':
    'The control plane projected the objective, constraints, workspace summary, and remaining work into a Capsule.',
  'timeline.description.handoffAcknowledgedLate':
    'The target Runtime did not establish Capsule acknowledgement before its first observable mutation action.',
  'timeline.description.handoffAcknowledged':
    'The target Runtime acknowledged the same Capsule before its first observable mutation action.',
  'timeline.description.effectRecorded':
    'The mutable workspace action received an identity before the Runtime executed it.',
  'timeline.description.effectStatus': 'Current Effect status: {status}.',
  'timeline.description.verificationPassed': 'The original completion criteria passed.',
  'timeline.description.verificationFailed': 'The original completion criteria did not pass.',
  'timeline.description.receiptVerified': 'All required criteria and Effect states are closed.',
  'timeline.description.receiptOther':
    'The Receipt preserves an unverified or indeterminate outcome.',
  'timeline.description.failureObserved':
    'Only an observed failure is recorded here; a hypothesis is not presented as the root cause.',
  'timeline.description.runtimeStarted': 'The native Runtime process started.',
  'timeline.description.runtimeFinished': 'The native Runtime process finished.',
  'timeline.description.kernelFallback':
    'This record comes from the Mission Kernel append-only event chain.',
  'timeline.description.branchCreated': 'Root Branch {branchId} now owns this execution history.',
  'timeline.description.catalogObserved':
    '{harness} inventory was observed with {availability} availability.',
  'timeline.description.profileDefinitionRecorded':
    'The reusable {harness} Profile Definition was recorded before execution.',
  'timeline.description.attemptBound':
    'Attempt {attemptId} was immutably bound to Branch, Contract, Profile Snapshot, workspace, and authority.',
  'timeline.description.runtimeEvent':
    '{harness} source #{sourceSequence} · {semanticKind} · native type {nativeEventType}.',
  'timeline.description.effectiveProfileReported':
    '{harness} reported {model} as the effective model for this Attempt.',
  'timeline.description.commandAccepted':
    'The {action} command entered the durable Mission command queue.',
  'timeline.description.commandStatus': 'The durable command is now {status}.',
  'timeline.defaultModel': 'default model',
  'event.mission.created': 'Mission created',
  'event.mission.status_changed': 'Mission status updated',
  'event.branch.created': 'Root Branch created',
  'event.runtime.catalog_observed': 'Runtime catalog observed',
  'event.profile.definition_recorded': 'Profile Definition recorded',
  'event.profile.selected': 'Runtime Profile selected',
  'event.attempt.bound': 'Attempt Binding recorded',
  'event.attempt.started': 'Attempt started',
  'event.attempt.finished': 'Attempt finished',
  'event.attempt.baseline': 'Workspace baseline recorded',
  'event.checkpoint.created': 'Checkpoint frozen',
  'event.handoff.prepared': 'Capsule prepared',
  'event.handoff.acknowledged': 'Capsule acknowledged',
  'event.handoff.rejected': 'Capsule rejected',
  'event.effect.recorded': 'Effect recorded',
  'event.effect.status_changed': 'Effect status updated',
  'event.runtime.process_started': 'Runtime process started',
  'event.runtime.process_finished': 'Runtime process finished',
  'event.runtime.event': 'Normalized Runtime event',
  'event.runtime.effective_profile_reported': 'Effective Runtime Profile reported',
  'event.command.accepted': 'Mission command accepted',
  'event.command.status_changed': 'Mission command status updated',
  'event.verification.completed': 'Completion criteria executed',
  'event.receipt.issued': 'Outcome Receipt issued',
  'event.failure.observed': 'Failure observed',
  'receipt.ariaLabel': 'Outcome Receipt',
  'receipt.eyebrow': 'Outcome Receipt',
  'receipt.verified': 'Outcome verified',
  'receipt.unverified': 'Outcome not verified',
  'receipt.idFallback': 'receipt id —',
  'receipt.criterionFallback': 'Unnamed completion criterion',
  'receipt.passed': 'PASSED',
  'receipt.unknown': 'UNKNOWN',
  'intelligence.eyebrow': 'Runtime intelligence',
  'intelligence.heading': 'The exact environment behind this Mission',
  'intelligence.rootBranch': 'Root Branch',
  'intelligence.profileDefinitions': 'Profile Definitions',
  'intelligence.profileSnapshots': 'Profile Snapshots',
  'intelligence.catalogObservations': 'Catalog Observations',
  'intelligence.attemptBindings': 'Attempt Bindings',
  'intelligence.effectiveProfileReports': 'Effective Profile Reports',
  'intelligence.runtimeEvents': 'Runtime event sources',
  'intelligence.notRecorded': 'Not recorded for this Mission.',
  'intelligence.oneRecord': '1 record',
  'intelligence.recordCount': '{count} records',
  'intelligence.viewRecord': 'View complete record',
  'intelligence.unknown': 'Unknown',
  'intelligence.unsupported': 'Unsupported',
  'intelligence.none': 'None',
  'intelligence.known': 'Known · {value}',
  'intelligence.partial': 'Partially observed · {value}',
  'intelligence.field.id': 'ID',
  'intelligence.field.harness': 'Harness',
  'intelligence.field.status': 'Status',
  'intelligence.field.parent': 'Parent',
  'intelligence.field.requestedModel': 'Requested model',
  'intelligence.field.reasoning': 'Reasoning',
  'intelligence.field.permission': 'Permission ceiling',
  'intelligence.field.budget': 'Injection budget',
  'intelligence.field.effectiveModel': 'Effective model',
  'intelligence.field.modelOverride': 'Model override',
  'intelligence.field.effectivePermissions': 'Effective permissions',
  'intelligence.field.instructions': 'Instructions',
  'intelligence.field.skills': 'Skills',
  'intelligence.field.mcpServers': 'MCP servers',
  'intelligence.field.contextWindow': 'Context window',
  'intelligence.field.session': 'Session',
  'intelligence.field.tools': 'Tools',
  'intelligence.field.version': 'Runtime version',
  'intelligence.field.digest': 'Configuration digest',
  'intelligence.field.availability': 'Availability',
  'intelligence.field.authentication': 'Authentication',
  'intelligence.field.quota': 'Quota',
  'intelligence.field.cost': 'Cost',
  'intelligence.field.observedAt': 'Observed at',
  'intelligence.field.attempt': 'Attempt',
  'intelligence.field.branch': 'Branch',
  'intelligence.field.profile': 'Profile Snapshot',
  'intelligence.field.contract': 'Contract',
  'intelligence.field.planNode': 'Plan node',
  'intelligence.field.authority': 'Authority',
  'intelligence.field.semanticKind': 'Semantic kind',
  'intelligence.field.nativeType': 'Native type',
  'intelligence.field.sourceSequence': 'Source sequence',
  'intelligence.field.causalParent': 'Causal parent',
  'intelligence.field.nativeArtifact': 'Native artifact',
  'intelligence.rootSource': 'source root',
  'error.cannotConnect':
    'Cannot reach the local MissionBraid service. Confirm that the app is still running.',
  'error.requestFailedStatus': 'The request did not complete. The service returned {status}.',
  'error.appStopping': 'The MissionBraid app is stopping.',
  'error.missionAlreadyRunning': 'Mission {missionId} already has a running operation.',
  'error.runtimeNotReady': '{harness} is not ready for Mission execution: {reason}',
  'error.routeNotFound': 'The requested app route was not found.',
  'error.invalidContentType': 'The request must use application/json.',
  'error.requestTooLarge': 'The request body is too large.',
  'error.invalidJson': 'The request body must be valid JSON.',
  'error.invalidMissionDraft': 'Mission input is invalid: {detail}',
  'error.credentialRejected': 'Credential-like content at {path} is not accepted.',
  'error.gitUnavailable': 'MissionBraid could not inspect the workspace with Git: {reason}',
  'artifact.view': 'View native evidence',
  'artifact.loading': 'Loading sanitized native evidence…',
  'artifact.heading': 'Sanitized native evidence',
  'artifact.close': 'Close evidence',
  'artifact.notFound': 'The referenced native artifact {artifactId} is not available.',
  'artifact.unavailable': 'Native evidence could not be loaded.',
  'artifact.mediaType': 'Media type',
  'artifact.sha256': 'SHA-256',
  'common.unknown': 'unknown',
  'common.unknownTime': 'Time unknown',
  'common.yes': 'Yes',
  'common.no': 'No',
  'footer.controlPlane': 'LOCAL CONTROL PLANE',
  'footer.kernelTruth': 'Mission Kernel is the sole source of truth for Mission state',
} as const;

export type AppCopyKey = keyof typeof EN_COPY;
export type AppCopy = Readonly<Record<AppCopyKey, string>>;

const ZH_CN_COPY = {
  'page.title': 'MissionBraid · Agent Runtime 工作台',
  'nav.skipToMission': '跳到 Mission 详情',
  'brand.eyebrow': 'Mission Runtime 工作台',
  'brand.subtitle': '任务属于 Mission，不属于某个 CLI。',
  'brand.continuity': 'MISSION 连续性',
  'language.ariaLabel': '语言',
  'connection.connecting': '正在连接本地控制面',
  'connection.connected': '本地控制面已连接',
  'connection.disconnected': '本地控制面未连接',
  'runtime.eyebrow': 'Runtime 清单',
  'runtime.heading': '本机运行环境',
  'runtime.refresh': '刷新清单',
  'runtime.loading': '正在识别 Codex、Qoder 与其他本机 Harness…',
  'runtime.empty': '没有发现 Runtime。安装并登录 Codex 或 Qoder 后刷新清单。',
  'runtime.nameFallback': 'Runtime',
  'runtime.versionFallback': '版本 —',
  'runtime.stateFallback': '状态未知',
  'runtime.status.ready-supported': '已就绪 · 可执行 Mission',
  'runtime.status.installed-unavailable': '已安装 · 当前不可用',
  'runtime.status.installed-unsupported': '已发现 · 尚未接入 Mission',
  'runtime.status.needs-bootstrap': '已发现外壳 · 需要启动命令',
  'runtime.status.missing': '本机未发现',
  'runtime.capabilitiesHeading': '适配器能力边界',
  'runtime.capability.observe': '观察',
  'runtime.capability.interrupt': '中断',
  'runtime.capability.steer': '转向',
  'runtime.capability.gate': '工具前门控',
  'runtime.capability.resume': '恢复会话',
  'runtime.capability.fork': '原生分叉',
  'runtime.capability.restore': '工作区恢复',
  'runtime.capability.effectControl': '副作用控制',
  'runtime.capability.status.supported': '已支持',
  'runtime.capability.status.unsupported': '不支持',
  'runtime.capability.status.unknown': '未知',
  'runtime.capability.control.native': '原生控制',
  'runtime.capability.control.controller': '控制面控制',
  'runtime.capability.control.cooperative': '协作式控制',
  'runtime.capability.control.observe-only': '仅观察',
  'runtime.capability.control.none': '无控制',
  'runtime.capability.control.unknown': '控制方式未知',
  'mission.indexEyebrow': 'Mission 索引',
  'mission.indexHeading': 'Mission',
  'mission.refreshAria': '刷新 Mission 列表',
  'mission.loading': '正在读取 Mission…',
  'mission.empty': '还没有 Mission。填写创建表单，让第一条任务开始跨 Runtime 流动。',
  'mission.untitled': '未命名 Mission',
  'mission.noSelectionEyebrow': '尚未选择 Mission',
  'mission.noSelectionTitle': '让一条任务穿过多个 Runtime',
  'mission.noSelectionBody':
    '选择左侧已有 Mission，或在右侧创建一条新 Mission。这里会按真实顺序展示 Attempt、Capsule、Effect 与 Receipt。',
  'mission.detailLoading': '正在读取 Mission 详情…',
  'mission.detailInvalid': 'Mission 详情格式无法识别。',
  'mission.objectiveMissing': '这条 Mission 没有可显示的目标摘要。',
  'mission.authoritativeEyebrow': '权威 Mission 状态',
  'mission.start': '开始执行',
  'mission.continue': '继续 Mission',
  'mission.reverify': '重新验收',
  'mission.lastRunFailed': '上一次执行未完成：{error}',
  'mission.lastRunErrorFallback': '未返回错误摘要',
  'mission.controllerInterrupted': '控制台在 Mission 完成前中断。可从最后一个持久化事件继续。',
  'mission.commandQueued': '命令已经持久进入队列，会在本地协调器领取后开始执行。',
  'mission.status.pending': '待运行',
  'mission.status.queued': '已排队',
  'mission.status.running': '运行中',
  'mission.status.waiting': '等待继续',
  'mission.status.verifying': '验收中',
  'mission.status.succeeded': '已验证',
  'mission.status.failed': '未通过',
  'mission.status.cancelled': '已取消',
  'mission.status.interrupted': '已中断 · 可继续',
  'mission.status.unknown': '未知',
  'composer.eyebrow': '创建',
  'composer.heading': '编织新 Mission',
  'composer.submitOnce': '一次提交',
  'form.titleLabel': '标题',
  'form.titlePlaceholder': '修复浏览器任务持久化',
  'form.objectiveLabel': '想得到什么结果',
  'form.objectivePlaceholder': '描述最终可验证的代码结果，不必替 Runtime 拆步骤。',
  'form.workspaceLabel': 'Git 工作区绝对路径',
  'form.workspacePlaceholder': '/Users/me/project-worktree',
  'form.verifierHeading': '完成判据',
  'form.verifierHint': '控制面会直接执行程序，不经过 Shell。',
  'form.executableLabel': '执行程序',
  'form.argumentsLabel': '参数 · 一行一个',
  'form.routeLegend': 'Runtime 路线',
  'form.singleAttempt': '单一 Attempt',
  'form.plannedHandoff': '计划内 Capsule 接力',
  'form.threeRuntimeHandoff': '三段 Capsule 接力',
  'form.profileSummary': 'Runtime Profile',
  'form.profileHint': 'Harness 只是运行器；模型、推理强度和权限共同构成实际执行环境。',
  'form.modelLabel': '模型',
  'form.reasoningLabel': '推理强度',
  'form.createAndRun': '创建并运行 Mission',
  'form.creating': '正在创建 Mission，并固定原始完成判据…',
  'form.created': 'Mission 已创建并开始执行。进度会出现在中间时间线。',
  'form.createFailed': 'Mission 未创建。检查输入后重试。',
  'validation.titleRequired': '标题不能为空。',
  'validation.objectiveRequired': '目标不能为空。',
  'validation.workspaceRequired': '工作区路径不能为空。',
  'validation.workspaceAbsolute': '工作区路径必须是绝对路径。',
  'validation.workspaceDirectory': '工作区路径必须指向一个目录。',
  'validation.workspaceGitRoot': '工作区路径必须是 Git Worktree 的根目录。',
  'validation.verifierRequired': '验收程序不能为空。',
  'validation.verifierDirect': '请直接运行验收程序，不要通过 Shell 执行。',
  'validation.codexModelRequired': 'Codex 模型不能为空。',
  'validation.codexReasoningRequired': 'Codex 推理强度不能为空。',
  'validation.qoderModelRequired': 'Qoder 模型不能为空。',
  'validation.qoderReasoningRequired': 'Qoder 推理强度不能为空。',
  'validation.claudeModelRequired': 'Claude Code 模型不能为空。',
  'validation.claudeReasoningRequired': 'Claude Code 推理强度不能为空。',
  'route.modelUnset': '模型未设置',
  'route.reasoningUnset': '推理强度未设置',
  'timeline.eyebrow': '证据时间线',
  'timeline.heading': 'Attempt · Capsule · Effect · Receipt',
  'timeline.oneEvent': '1 条事件',
  'timeline.manyEvents': '{count} 条事件',
  'timeline.pending': 'Mission 已创建，开始执行后这里会出现真实事件。',
  'timeline.empty': '当前 API 没有返回可显示的时间线。',
  'timeline.recordFallback': '运行记录',
  'timeline.viewKernelRecord': '查看 Kernel 记录',
  'timeline.unserializable': '记录无法序列化',
  'timeline.description.attemptStarted': '{harness} 开始执行当前阶段。',
  'timeline.description.attemptFinished': '当前 Attempt 已留下可追溯结果。',
  'timeline.description.profileSelected': '{harness} 使用 {model} Profile。',
  'timeline.description.checkpointCreated':
    '工作区状态已冻结，后续 Runtime 将从这条可验证边界继续。',
  'timeline.description.handoffPrepared':
    '控制面已把目标、约束、工作区摘要和剩余工作投影为 Capsule。',
  'timeline.description.handoffAcknowledgedLate':
    '目标 Runtime 未能证明在第一个可观察的变更动作前确认 Capsule。',
  'timeline.description.handoffAcknowledged':
    '目标 Runtime 已在第一个可观察的变更动作前确认同一 Capsule。',
  'timeline.description.effectRecorded': '可变工作区动作已先登记身份，再交给 Runtime 执行。',
  'timeline.description.effectStatus': 'Effect 当前状态：{status}。',
  'timeline.description.verificationPassed': '原始完成判据已通过。',
  'timeline.description.verificationFailed': '原始完成判据未通过。',
  'timeline.description.receiptVerified': '所有必要判据和 Effect 状态已闭合。',
  'timeline.description.receiptOther': 'Receipt 保留了未通过或未确定的结果。',
  'timeline.description.failureObserved': '这里只记录已经观察到的故障，不把推测冒充根因。',
  'timeline.description.runtimeStarted': '真实 Runtime 进程已经启动。',
  'timeline.description.runtimeFinished': '真实 Runtime 进程已经结束。',
  'timeline.description.kernelFallback': '这条记录来自 Mission Kernel 的追加事件链。',
  'timeline.description.branchCreated': 'Root Branch {branchId} 开始持有这条执行历史。',
  'timeline.description.catalogObserved':
    '已观察 {harness} 的 Runtime 清单状态，可用性为 {availability}。',
  'timeline.description.profileDefinitionRecorded':
    '执行前已经记录可复用的 {harness} Profile Definition。',
  'timeline.description.attemptBound':
    'Attempt {attemptId} 已与 Branch、Contract、Profile Snapshot、工作区和权限形成不可变绑定。',
  'timeline.description.runtimeEvent':
    '{harness} 源序号 #{sourceSequence} · {semanticKind} · Native 类型 {nativeEventType}。',
  'timeline.description.effectiveProfileReported':
    '{harness} 报告这个 Attempt 的实际生效模型为 {model}。',
  'timeline.description.commandAccepted': '{action} 命令已经进入持久 Mission 命令队列。',
  'timeline.description.commandStatus': '持久命令当前状态为 {status}。',
  'timeline.defaultModel': '默认模型',
  'event.mission.created': 'Mission 已创建',
  'event.mission.status_changed': 'Mission 状态更新',
  'event.branch.created': 'Root Branch 已创建',
  'event.runtime.catalog_observed': 'Runtime 清单观察已记录',
  'event.profile.definition_recorded': 'Profile Definition 已记录',
  'event.profile.selected': 'Runtime Profile 已选择',
  'event.attempt.bound': 'Attempt Binding 已记录',
  'event.attempt.started': 'Attempt 已开始',
  'event.attempt.finished': 'Attempt 已结束',
  'event.attempt.baseline': '工作区基线已记录',
  'event.checkpoint.created': 'Checkpoint 已冻结',
  'event.handoff.prepared': 'Capsule 已准备',
  'event.handoff.acknowledged': 'Capsule 已确认',
  'event.handoff.rejected': 'Capsule 被拒绝',
  'event.effect.recorded': 'Effect 已登记',
  'event.effect.status_changed': 'Effect 状态更新',
  'event.runtime.process_started': 'Runtime 进程已启动',
  'event.runtime.process_finished': 'Runtime 进程已结束',
  'event.runtime.event': '归一化 Runtime 事件',
  'event.runtime.effective_profile_reported': '实际生效 Runtime Profile 已报告',
  'event.command.accepted': 'Mission 命令已接收',
  'event.command.status_changed': 'Mission 命令状态已更新',
  'event.verification.completed': '完成判据已执行',
  'event.receipt.issued': 'Outcome Receipt 已签发',
  'event.failure.observed': '已观察到故障',
  'receipt.ariaLabel': 'Outcome Receipt',
  'receipt.eyebrow': 'Outcome Receipt',
  'receipt.verified': '结果已经验证',
  'receipt.unverified': '结果未被验证',
  'receipt.idFallback': 'Receipt ID —',
  'receipt.criterionFallback': '未命名完成判据',
  'receipt.passed': '已通过',
  'receipt.unknown': '未知',
  'intelligence.eyebrow': 'Runtime 情报',
  'intelligence.heading': '这条 Mission 背后的真实执行环境',
  'intelligence.rootBranch': 'Root Branch',
  'intelligence.profileDefinitions': 'Profile Definition',
  'intelligence.profileSnapshots': 'Profile Snapshot',
  'intelligence.catalogObservations': 'Catalog Observation',
  'intelligence.attemptBindings': 'Attempt Binding',
  'intelligence.effectiveProfileReports': '实际生效 Profile 报告',
  'intelligence.runtimeEvents': 'Runtime 事件来源',
  'intelligence.notRecorded': '这条 Mission 尚未记录此类信息。',
  'intelligence.oneRecord': '1 条记录',
  'intelligence.recordCount': '{count} 条记录',
  'intelligence.viewRecord': '查看完整记录',
  'intelligence.unknown': '未知',
  'intelligence.unsupported': '不支持',
  'intelligence.none': '无',
  'intelligence.known': '已知 · {value}',
  'intelligence.partial': '部分可见 · {value}',
  'intelligence.field.id': 'ID',
  'intelligence.field.harness': 'Harness',
  'intelligence.field.status': '状态',
  'intelligence.field.parent': '父级',
  'intelligence.field.requestedModel': '请求模型',
  'intelligence.field.reasoning': '推理强度',
  'intelligence.field.permission': '权限上限',
  'intelligence.field.budget': '注入预算',
  'intelligence.field.effectiveModel': '生效模型',
  'intelligence.field.modelOverride': '模型是否被改写',
  'intelligence.field.effectivePermissions': '生效权限',
  'intelligence.field.instructions': '指令文件',
  'intelligence.field.skills': 'Skills',
  'intelligence.field.mcpServers': 'MCP 服务',
  'intelligence.field.contextWindow': '上下文窗口',
  'intelligence.field.session': '会话',
  'intelligence.field.tools': '工具',
  'intelligence.field.version': 'Runtime 版本',
  'intelligence.field.digest': '配置摘要',
  'intelligence.field.availability': '可用性',
  'intelligence.field.authentication': '认证状态',
  'intelligence.field.quota': '额度',
  'intelligence.field.cost': '成本',
  'intelligence.field.observedAt': '观察时间',
  'intelligence.field.attempt': 'Attempt',
  'intelligence.field.branch': 'Branch',
  'intelligence.field.profile': 'Profile Snapshot',
  'intelligence.field.contract': 'Contract',
  'intelligence.field.planNode': 'Plan 节点',
  'intelligence.field.authority': '权限',
  'intelligence.field.semanticKind': '语义类型',
  'intelligence.field.nativeType': 'Native 类型',
  'intelligence.field.sourceSequence': '源序号',
  'intelligence.field.causalParent': '因果父事件',
  'intelligence.field.nativeArtifact': 'Native Artifact',
  'intelligence.rootSource': '源头事件',
  'error.cannotConnect': '无法连接本地 MissionBraid 服务。确认 app 服务仍在运行。',
  'error.requestFailedStatus': '请求未完成，服务返回 {status}。',
  'error.appStopping': 'MissionBraid app 正在停止。',
  'error.missionAlreadyRunning': 'Mission {missionId} 已有正在运行的操作。',
  'error.runtimeNotReady': '{harness} 尚不能执行 Mission：{reason}',
  'error.routeNotFound': '没有找到请求的 app 路由。',
  'error.invalidContentType': '请求必须使用 application/json。',
  'error.requestTooLarge': '请求内容过大。',
  'error.invalidJson': '请求内容必须是有效的 JSON。',
  'error.invalidMissionDraft': 'Mission 输入无效：{detail}',
  'error.credentialRejected': '不接受 {path} 中疑似凭据的内容。',
  'error.gitUnavailable': 'MissionBraid 无法使用 Git 检查工作区：{reason}',
  'artifact.view': '查看原生证据',
  'artifact.loading': '正在加载脱敏后的原生证据…',
  'artifact.heading': '脱敏后的原生证据',
  'artifact.close': '关闭证据',
  'artifact.notFound': '引用的原生 Artifact {artifactId} 当前不可用。',
  'artifact.unavailable': '无法加载原生证据。',
  'artifact.mediaType': '媒体类型',
  'artifact.sha256': 'SHA-256',
  'common.unknown': '未知',
  'common.unknownTime': '时间未知',
  'common.yes': '是',
  'common.no': '否',
  'footer.controlPlane': '本地控制面',
  'footer.kernelTruth': 'Mission Kernel 是任务状态的唯一事实源',
} as const satisfies AppCopy;

export const APP_COPY = {
  en: EN_COPY,
  'zh-CN': ZH_CN_COPY,
} as const;

export type AppLocale = keyof typeof APP_COPY;
export const APP_LOCALES = Object.freeze(Object.keys(APP_COPY) as AppLocale[]);
